version: "3.8"

services:
  web:
    build: .
    command: gunicorn spartagora.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    working_dir: /usr/src/app/
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:14.4-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    env_file:
      - ./.env.postgres
volumes:
  postgres_db:
